### PR TITLE
Keep final framework files at root

### PR DESCRIPTION
**Pull request by mauromorales**
This is how the previous images where built and I think it's probably better to keep it that way since there's nothing else in the image

### CODE REVIEW

**Comment by Itxaka** [comment]
I think this is not correct as we copy from the framework dir in kairos no?

And there was some limitations on copying from / no?

**Comment by mauromorales** [comment]
> I think this is not correct as we copy from the framework dir in kairos no?
> 
> And there was some limitations on copying from / no?

Good quesiton, I'm not aware of this

So the way it looks inside the `/framework` is this:

```
boot    etc     system  usr     var
```

And what we do on the Kairos side is that we copy that at the root level

https://github.com/kairos-io/kairos/blob/master/images/Dockerfile.kairos#L11

Which I guess makes sense because it follows the traditional directory structure. But I'm not aware of the issues that could come from this.

What would be the alternative?

**Comment by jimmykarily** [comment]
> I think this is not correct as we copy from the framework dir in kairos no?
> 
> And there was some limitations on copying from / no?

Maybe you remember this? https://github.com/GoogleContainerTools/kaniko/issues/1007
We faced this here: https://github.com/kairos-io/osbuilder/blob/429e9be933e762d732c096b495cdf2959cc76450/tools-image/enki/pkg/action/converter.go#L112-L114

**Comment by mauromorales** [comment]
@jimmykarily @Itxaka thanks guys, I'm not sure how to proceed here then. So I will open a different ticket to investigate this further because so far, this is how it works on the framework image and Kairos side. I think I would rather merge this and start consuming the new framework images and keep whatever existing issue we have than try to solve it here and let them diverge.

**Review by Itxaka — APPROVED** [review]

**Comment by mauromorales** [comment]
https://github.com/kairos-io/kairos/issues/2076

**Comment by jimmykarily** [comment]
You can safely ignore the kaniko issue if it's relevant. We have a workaround.

**Pull request merged**
